// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v3.12.4
// source: forTest.proto

package testProto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CappuccinoInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Milk  string `protobuf:"bytes,1,opt,name=milk,proto3" json:"milk,omitempty"`
	Beans string `protobuf:"bytes,2,opt,name=beans,proto3" json:"beans,omitempty"`
}

func (x *CappuccinoInput) Reset() {
	*x = CappuccinoInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forTest_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CappuccinoInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CappuccinoInput) ProtoMessage() {}

func (x *CappuccinoInput) ProtoReflect() protoreflect.Message {
	mi := &file_forTest_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CappuccinoInput.ProtoReflect.Descriptor instead.
func (*CappuccinoInput) Descriptor() ([]byte, []int) {
	return file_forTest_proto_rawDescGZIP(), []int{0}
}

func (x *CappuccinoInput) GetMilk() string {
	if x != nil {
		return x.Milk
	}
	return ""
}

func (x *CappuccinoInput) GetBeans() string {
	if x != nil {
		return x.Beans
	}
	return ""
}

type CappuccinoOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cappuccino string `protobuf:"bytes,1,opt,name=cappuccino,proto3" json:"cappuccino,omitempty"`
}

func (x *CappuccinoOutput) Reset() {
	*x = CappuccinoOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forTest_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CappuccinoOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CappuccinoOutput) ProtoMessage() {}

func (x *CappuccinoOutput) ProtoReflect() protoreflect.Message {
	mi := &file_forTest_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CappuccinoOutput.ProtoReflect.Descriptor instead.
func (*CappuccinoOutput) Descriptor() ([]byte, []int) {
	return file_forTest_proto_rawDescGZIP(), []int{1}
}

func (x *CappuccinoOutput) GetCappuccino() string {
	if x != nil {
		return x.Cappuccino
	}
	return ""
}

type TiramisuInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cheese string `protobuf:"bytes,1,opt,name=cheese,proto3" json:"cheese,omitempty"`
	Wine   string `protobuf:"bytes,2,opt,name=wine,proto3" json:"wine,omitempty"`
	Coffee string `protobuf:"bytes,3,opt,name=coffee,proto3" json:"coffee,omitempty"`
}

func (x *TiramisuInput) Reset() {
	*x = TiramisuInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forTest_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TiramisuInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiramisuInput) ProtoMessage() {}

func (x *TiramisuInput) ProtoReflect() protoreflect.Message {
	mi := &file_forTest_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiramisuInput.ProtoReflect.Descriptor instead.
func (*TiramisuInput) Descriptor() ([]byte, []int) {
	return file_forTest_proto_rawDescGZIP(), []int{2}
}

func (x *TiramisuInput) GetCheese() string {
	if x != nil {
		return x.Cheese
	}
	return ""
}

func (x *TiramisuInput) GetWine() string {
	if x != nil {
		return x.Wine
	}
	return ""
}

func (x *TiramisuInput) GetCoffee() string {
	if x != nil {
		return x.Coffee
	}
	return ""
}

type TiramisuOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tiramisu string `protobuf:"bytes,1,opt,name=tiramisu,proto3" json:"tiramisu,omitempty"`
}

func (x *TiramisuOutput) Reset() {
	*x = TiramisuOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forTest_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TiramisuOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TiramisuOutput) ProtoMessage() {}

func (x *TiramisuOutput) ProtoReflect() protoreflect.Message {
	mi := &file_forTest_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TiramisuOutput.ProtoReflect.Descriptor instead.
func (*TiramisuOutput) Descriptor() ([]byte, []int) {
	return file_forTest_proto_rawDescGZIP(), []int{3}
}

func (x *TiramisuOutput) GetTiramisu() string {
	if x != nil {
		return x.Tiramisu
	}
	return ""
}

type SetInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cappuccino *CappuccinoInput `protobuf:"bytes,1,opt,name=cappuccino,proto3" json:"cappuccino,omitempty"`
	Tiramisu   *TiramisuInput   `protobuf:"bytes,2,opt,name=tiramisu,proto3" json:"tiramisu,omitempty"`
}

func (x *SetInput) Reset() {
	*x = SetInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forTest_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetInput) ProtoMessage() {}

func (x *SetInput) ProtoReflect() protoreflect.Message {
	mi := &file_forTest_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetInput.ProtoReflect.Descriptor instead.
func (*SetInput) Descriptor() ([]byte, []int) {
	return file_forTest_proto_rawDescGZIP(), []int{4}
}

func (x *SetInput) GetCappuccino() *CappuccinoInput {
	if x != nil {
		return x.Cappuccino
	}
	return nil
}

func (x *SetInput) GetTiramisu() *TiramisuInput {
	if x != nil {
		return x.Tiramisu
	}
	return nil
}

type SetOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Cappuccino *CappuccinoOutput `protobuf:"bytes,1,opt,name=cappuccino,proto3" json:"cappuccino,omitempty"`
	Tiramisu   *TiramisuOutput   `protobuf:"bytes,2,opt,name=tiramisu,proto3" json:"tiramisu,omitempty"`
}

func (x *SetOutput) Reset() {
	*x = SetOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_forTest_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetOutput) ProtoMessage() {}

func (x *SetOutput) ProtoReflect() protoreflect.Message {
	mi := &file_forTest_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetOutput.ProtoReflect.Descriptor instead.
func (*SetOutput) Descriptor() ([]byte, []int) {
	return file_forTest_proto_rawDescGZIP(), []int{5}
}

func (x *SetOutput) GetCappuccino() *CappuccinoOutput {
	if x != nil {
		return x.Cappuccino
	}
	return nil
}

func (x *SetOutput) GetTiramisu() *TiramisuOutput {
	if x != nil {
		return x.Tiramisu
	}
	return nil
}

var File_forTest_proto protoreflect.FileDescriptor

var file_forTest_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x6f, 0x72, 0x54, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x3b, 0x0a, 0x0f, 0x43, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f, 0x49, 0x6e, 0x70,
	0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6d, 0x69, 0x6c, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6d, 0x69, 0x6c, 0x6b, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x61, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x62, 0x65, 0x61, 0x6e, 0x73, 0x22, 0x32, 0x0a, 0x10,
	0x43, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f,
	0x22, 0x53, 0x0a, 0x0d, 0x54, 0x69, 0x72, 0x61, 0x6d, 0x69, 0x73, 0x75, 0x49, 0x6e, 0x70, 0x75,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x65, 0x65, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x63, 0x68, 0x65, 0x65, 0x73, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x77, 0x69, 0x6e,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77, 0x69, 0x6e, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x63, 0x6f, 0x66, 0x66, 0x65, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63,
	0x6f, 0x66, 0x66, 0x65, 0x65, 0x22, 0x2c, 0x0a, 0x0e, 0x54, 0x69, 0x72, 0x61, 0x6d, 0x69, 0x73,
	0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x74, 0x69, 0x72, 0x61, 0x6d,
	0x69, 0x73, 0x75, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x69, 0x72, 0x61, 0x6d,
	0x69, 0x73, 0x75, 0x22, 0x68, 0x0a, 0x08, 0x53, 0x65, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12,
	0x30, 0x0a, 0x0a, 0x63, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x43, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f,
	0x49, 0x6e, 0x70, 0x75, 0x74, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e,
	0x6f, 0x12, 0x2a, 0x0a, 0x08, 0x74, 0x69, 0x72, 0x61, 0x6d, 0x69, 0x73, 0x75, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x54, 0x69, 0x72, 0x61, 0x6d, 0x69, 0x73, 0x75, 0x49, 0x6e,
	0x70, 0x75, 0x74, 0x52, 0x08, 0x74, 0x69, 0x72, 0x61, 0x6d, 0x69, 0x73, 0x75, 0x22, 0x6b, 0x0a,
	0x09, 0x53, 0x65, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x31, 0x0a, 0x0a, 0x63, 0x61,
	0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11,
	0x2e, 0x43, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x52, 0x0a, 0x63, 0x61, 0x70, 0x70, 0x75, 0x63, 0x63, 0x69, 0x6e, 0x6f, 0x12, 0x2b, 0x0a,
	0x08, 0x74, 0x69, 0x72, 0x61, 0x6d, 0x69, 0x73, 0x75, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x54, 0x69, 0x72, 0x61, 0x6d, 0x69, 0x73, 0x75, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74,
	0x52, 0x08, 0x74, 0x69, 0x72, 0x61, 0x6d, 0x69, 0x73, 0x75, 0x42, 0x11, 0x5a, 0x0f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_forTest_proto_rawDescOnce sync.Once
	file_forTest_proto_rawDescData = file_forTest_proto_rawDesc
)

func file_forTest_proto_rawDescGZIP() []byte {
	file_forTest_proto_rawDescOnce.Do(func() {
		file_forTest_proto_rawDescData = protoimpl.X.CompressGZIP(file_forTest_proto_rawDescData)
	})
	return file_forTest_proto_rawDescData
}

var file_forTest_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_forTest_proto_goTypes = []interface{}{
	(*CappuccinoInput)(nil),  // 0: CappuccinoInput
	(*CappuccinoOutput)(nil), // 1: CappuccinoOutput
	(*TiramisuInput)(nil),    // 2: TiramisuInput
	(*TiramisuOutput)(nil),   // 3: TiramisuOutput
	(*SetInput)(nil),         // 4: SetInput
	(*SetOutput)(nil),        // 5: SetOutput
}
var file_forTest_proto_depIdxs = []int32{
	0, // 0: SetInput.cappuccino:type_name -> CappuccinoInput
	2, // 1: SetInput.tiramisu:type_name -> TiramisuInput
	1, // 2: SetOutput.cappuccino:type_name -> CappuccinoOutput
	3, // 3: SetOutput.tiramisu:type_name -> TiramisuOutput
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_forTest_proto_init() }
func file_forTest_proto_init() {
	if File_forTest_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_forTest_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CappuccinoInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forTest_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CappuccinoOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forTest_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TiramisuInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forTest_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TiramisuOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forTest_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_forTest_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_forTest_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_forTest_proto_goTypes,
		DependencyIndexes: file_forTest_proto_depIdxs,
		MessageInfos:      file_forTest_proto_msgTypes,
	}.Build()
	File_forTest_proto = out.File
	file_forTest_proto_rawDesc = nil
	file_forTest_proto_goTypes = nil
	file_forTest_proto_depIdxs = nil
}
